services:
  label-printer:
    image: ghcr.io/flyingt/seabird-p1-12a:latest
    container_name: seabird-label-printer
    ports:
      - "8081:80"
      - "8443:443"
    environment:
      - HTTPS_PORT=8443
    restart: unless-stopped
